apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
data:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "8080"
  ALLOWED_ORIGINS: "http://20.249.133.81"
  JPA_DDL_AUTO: update
  JPA_SHOW_SQL: "true"

