apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
stringData:
  JWT_SECRET_KEY: "+B3wreyJBw682DDNLHn7R/9r80F2UxJGz6XePH4vDgen9eYj2dpoQcc6+It1HOT2
UFftm0FXsvE2ryvJJT4R7Q=="
  JWT_ACCESS_TOKEN_VALIDITY: "3600000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"
